dataset: ImageNet10

dataset_path: dataset/imagenet10

num_classes: 10

batch_size: 64

epochs: 30

image_size: 224

learning_rate: 0.0001

weight_decay: 0.0001

model:
    name: convnext_tiny
    pretrained: true

optimizer:
    AdamW

scheduler:
    cosine

augmentation:
    flip: true
    color_jitter: true
    random_crop: true
